In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
# load dataset into Pandas DataFrame
df = pd.read_csv(url, names=['sepal length','sepal width','petal length','petal width','target'])

In [3]:
feature = ['sepal length', 'sepal width', 'petal length', 'petal width']

# separating features
x = df.loc[:,feature]

# separating target
y = df.loc[:,'target']

#Standardising features
x = StandardScaler().fit_transform(x)

In [8]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
X1 = np.array(x)
y1 = np.array(y)
lda = LinearDiscriminantAnalysis()
lda.fit(X1, y1)

LinearDiscriminantAnalysis()

In [9]:

df11=pd.DataFrame(lda.coef_[0].reshape(-1,1),feature,columns=["Weight"])
df12=pd.DataFrame(lda.intercept_[0].reshape(-1,1),["Bias"],columns=["Weight"])
resulty = pd.concat([df12, df11], axis=0)
resulty

                 Weight
Bias         -30.119977
sepal length   5.155010
sepal width    5.292114
petal length -29.609120
petal width  -16.077246

In [12]:
from sklearn import metrics
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size=0.3, random_state=42, stratify=y)
lda = LinearDiscriminantAnalysis()
X_train1 = np.array(X_train)
y_train1 = np.array(y_train)
lda.fit(X_train1, y_train1)
df11=pd.DataFrame(lda.coef_[0].reshape(-1,1),feature,columns=["Weight"])
df12=pd.DataFrame(lda.intercept_[0].reshape(-1,1),["Bias"],columns=["Weight"])
params = pd.concat([df12, df11], axis=0)
params

                 Weight
Bias         -29.048991
sepal length   4.800682
sepal width    4.582753
petal length -27.552602
petal width  -17.355879

In [13]:
from sklearn.metrics import accuracy_score
X_test1 = np.array(X_test)
y_test1 = np.array(y_test)
y_pred = lda.predict(X_test1)
print('Accuracy of Linear Discriminant Analysis Model on test set: {:.2f}'.format(accuracy_score(y_test, y_pred)))

Accuracy of Linear Discriminant Analysis Model on test set: 0.98